# Generated by Django 4.1.1 on 2024-05-30 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='files',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.CharField(max_length=30)),
                ('ACCNO', models.CharField(max_length=30)),
                ('CustState', models.CharField(max_length=100)),
                ('CustPin', models.IntegerField()),
                ('DPD', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='uploader',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('About', models.CharField(max_length=500)),
                ('File', models.FileField(upload_to='file')),
            ],
        ),
    ]
