# Generated by Django 4.1.1 on 2024-05-31 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='files',
            name='ACCNO',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='files',
            name='CustState',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='files',
            name='Date',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
