# Generated by Django 4.1.1 on 2024-05-31 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0002_alter_files_accno_alter_files_custstate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='files',
            name='CustPin',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='files',
            name='DPD',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
