# Generated by Django 4.1.1 on 2024-05-31 05:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0003_alter_files_custpin_alter_files_dpd'),
    ]

    operations = [
        migrations.RenameField(
            model_name='files',
            old_name='CustPin',
            new_name='Cust_Pin',
        ),
        migrations.RenameField(
            model_name='files',
            old_name='CustState',
            new_name='Cust_State',
        ),
    ]
