# Generated by Django 4.1.1 on 2024-05-31 05:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0004_rename_custpin_files_cust_pin_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='files',
            old_name='Cust_Pin',
            new_name='CustPin',
        ),
        migrations.RenameField(
            model_name='files',
            old_name='Cust_State',
            new_name='CustState',
        ),
    ]
